#!/usr/bin/env python
# To use: put this file under /usr/local/bin or where ever your $PATH is happy with...
# Then execute: 'sudo chmod +x /usr/local/bin/realpath'
import sys
import os.path

def print_help():
	print "Usage: realpath /path/to/file"

if __name__ == "__main__":
	if len(sys.argv) is 1:
		print_help()

	else:
		for i in xrange(1, len(sys.argv)):
			filepath = str(sys.argv[i])

			if os.path.exists(filepath):
				print os.path.abspath(filepath)
				if os.path.islink(filepath):
					print os.path.realpath(filepath)
			else:
				print filepath + " does not exist!"
