#!/usr/bin/env python
# To use: put this file under /usr/local/bin or where ever your 
# $PATH is happy with...
# Then execute: 
# 'sudo chmod +x /usr/local/bin/realpath'
import sys
import os.path

def print_help():
	print "Usage: realapth /path/to/file"

if len(sys.argv) is not 2:
	print_help()

filepath = str(sys.argv[1])

if os.path.exists(filepath):
	abspath = os.path.abspath(filepath)
	print abspath
else:
	print filepath + " does not exist!"